name: Update memes.md

on:
  push:
    branches:
      - "main"
    paths:
      - "memes/**"

jobs:
  update-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt install python3-pip
          pip3 install -U meme_generator

      - name: Install fonts
        run: |
          sudo apt install fonts-noto-cjk fonts-noto-color-emoji
          sudo locale-gen zh_CN zh_CN.UTF-8
          sudo update-locale LC_ALL=zh_CN.UTF-8 LANG=zh_CN.UTF-8
          sudo mkdir /usr/share/fonts/myfonts
          sudo cp resources/fonts/* /usr/share/fonts/myfonts/
          fc-cache -fv

      - name: Change config
        run: |
          mkdir -p ~/.config/meme_generator
          echo "[meme]\nload_builtin_memes = false\nmeme_dirs = [\"$GITHUB_WORKSPACE/memes\"]" > ~/.config/meme_generator/config.toml

      - name: Update memes.md
        run: python3 docs/update_doc.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "main"
